language: ruby

rvm:
  - 2.1.1
  - 2.0.0
  - jruby-head

services:
  - mongodb
  - redis-server

before_script
  - npm install dashku-web
  - TEST_USER_PATH=/tmp npm run dashku-web generateTestUser
  - NODE_ENV=test npm run dashku-web regenerateApiKeyDb
  - NODE_ENV=test npm run dashku-web start & sleep 5  